{% set name = "pynucos" %}
{% set version = "2.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NOAA-ORR-ERD/PyNUCOS/archive/v{{ version }}.tar.gz
  sha256: 9b4a932eb4d3fd650f8e70c63297ce128b4b360f14c732294f3bca707f6509b3


build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  requires:
    - pytest
  imports:
    - unit_conversion
  commands: pytest --pyargs unit_conversion

about:
  home: https://github.com/NOAA-ORR-ERD/PyNUCOS
  license: CC0-1.0
  license_file: LICENSE.txt
  summary: Python NOAA Unit Converter for Oil Spills
  description: |
    Python NOAA Unit Converter for Oil Spills provides a python package for
    doing physical unit conversion. It includes the odd units (API gravity,
    etc) that are used for oil spill response and planning, but not the odd
    units that other fields may require.
    It also includes many common units for general use.
  dev_url: https://github.com/NOAA-ORR-ERD/PyNUCOS

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
