{% set name = "pynucos" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NOAA-ORR-ERD/PyNUCOS/archive/v{{ version }}.tar.gz
  sha256: 7e88d5501d19d47e278d1732fd889e9206c71f5789f6f3cc4b607dbf9b6e02fb


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  requires:
    - pytest
  imports:
    - unit_conversion
  commands: pytest --pyargs nucos

about:
  home: https://github.com/NOAA-ORR-ERD/PyNUCOS
  license: CC0-1.0
  license_file: LICENSE.txt
  summary: Python NOAA Unit Converter for Oil Spills
  description: |
    Python NOAA Unit Converter for Oil Spills provides a python package for
    doing physical unit conversion. It includes the odd units (API gravity,
    etc) that are used for oil spill response and planning, but not the odd
    units that other fields may require.
    It also includes many common units for general use.
  dev_url: https://github.com/NOAA-ORR-ERD/PyNUCOS

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
